# Generated by Django 5.2.13 on 2026-04-28 10:45

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('min_order_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(blank=True, upload_to='products/water-bottles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StickerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('supplier', 'Supplier'), ('custom', 'Custom')], max_length=20)),
                ('template_image', models.ImageField(blank=True, upload_to='products/sticker-templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sticker_options', to='products.product')),
            ],
            options={
                'ordering': ['product_id', 'type'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['supplier', 'name'], name='products_supplier_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price_per_unit'], name='products_price_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='products_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('supplier'), name='products_supplier_name_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_unit__gt', 0)), name='products_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('min_order_quantity__gte', 1)), name='products_min_order_gte_1'),
        ),
        migrations.AddIndex(
            model_name='stickeroption',
            index=models.Index(fields=['product', 'type'], name='sticker_product_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='stickeroption',
            constraint=models.UniqueConstraint(fields=('product', 'type'), name='sticker_unique_type_per_product'),
        ),
    ]
