# Generated by Django 5.2.13 on 2026-04-28 10:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('payment_pending', 'Payment Pending'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='payment_pending', max_length=20)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('receipt', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('payment_provider', models.CharField(default='razorpay', max_length=32)),
                ('payment_status', models.CharField(choices=[('created', 'Created'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=20)),
                ('payment_order_id', models.CharField(blank=True, max_length=64)),
                ('payment_id', models.CharField(blank=True, max_length=64)),
                ('payment_signature', models.CharField(blank=True, max_length=128)),
                ('payment_failure_reason', models.CharField(blank=True, max_length=255)),
                ('payment_captured_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='suppliers.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sticker_type', models.CharField(choices=[('supplier', 'Supplier'), ('custom', 'Custom')], max_length=20)),
                ('custom_text', models.CharField(blank=True, max_length=255)),
                ('custom_image', models.ImageField(blank=True, upload_to='orders/custom-stickers/')),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['assigned_supplier', 'status'], name='orders_supplier_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='orders_payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_order_id'], name='orders_payment_order_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='orders_total_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_order_id', ''), _negated=True), fields=('payment_order_id',), name='orders_payment_order_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_id', ''), _negated=True), fields=('payment_id',), name='orders_payment_id_unique'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='order_items_order_product_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['sticker_type'], name='order_items_sticker_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_items_quantity_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_snapshot__gte', 0)), name='order_items_unit_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='order_items_line_total_gte_0'),
        ),
    ]
