# Generated by Codex on 2026-05-26

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="commission_percentage_snapshot",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))]),
        ),
        migrations.AddField(
            model_name="order",
            name="commission_revenue",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))]),
        ),
        migrations.AddField(
            model_name="order",
            name="customization_total",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))]),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_cost",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))]),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_margin_revenue",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))]),
        ),
        migrations.AddField(
            model_name="order",
            name="platform_revenue",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))]),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal_price",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))]),
        ),
        migrations.AddField(
            model_name="order",
            name="supplier_payout",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))]),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="customization_total",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="sticker_fee_snapshot",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(condition=models.Q(("subtotal_price__gte", 0)), name="orders_subtotal_price_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(condition=models.Q(("customization_total__gte", 0)), name="orders_custom_total_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(condition=models.Q(("delivery_cost__gte", 0)), name="orders_delivery_cost_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(condition=models.Q(("commission_revenue__gte", 0)), name="orders_commission_revenue_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(condition=models.Q(("delivery_margin_revenue__gte", 0)), name="orders_delivery_margin_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(condition=models.Q(("platform_revenue__gte", 0)), name="orders_platform_revenue_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(condition=models.Q(("supplier_payout__gte", 0)), name="orders_supplier_payout_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(condition=models.Q(("sticker_fee_snapshot__gte", 0)), name="order_items_sticker_fee_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(condition=models.Q(("customization_total__gte", 0)), name="order_items_custom_total_gte_0"),
        ),
    ]
