# Generated by Codex on 2026-05-26

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def seed_default_revenue_config(apps, schema_editor):
    CommissionConfig = apps.get_model("revenue", "CommissionConfig")
    StickerPricing = apps.get_model("revenue", "StickerPricing")

    CommissionConfig.objects.get_or_create(
        active=True,
        defaults={
            "commission_percentage": Decimal("12.00"),
            "delivery_margin_percentage": Decimal("0.00"),
            "delivery_margin_active": False,
        },
    )
    StickerPricing.objects.get_or_create(
        sticker_type="supplier",
        active=True,
        defaults={
            "pricing_mode": "free",
            "price_per_bottle": Decimal("0.00"),
            "minimum_price_per_bottle": Decimal("0.00"),
            "maximum_price_per_bottle": Decimal("0.00"),
        },
    )
    StickerPricing.objects.get_or_create(
        sticker_type="custom",
        active=True,
        defaults={
            "pricing_mode": "range",
            "price_per_bottle": Decimal("4.00"),
            "minimum_price_per_bottle": Decimal("2.00"),
            "maximum_price_per_bottle": Decimal("5.00"),
        },
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_revenue_snapshots"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("commission_percentage", models.DecimalField(decimal_places=2, default=Decimal("12.00"), max_digits=5)),
                ("delivery_margin_percentage", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5)),
                ("delivery_margin_active", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="PromotedListing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("promotion_type", models.CharField(choices=[("featured_listing", "Featured listing"), ("homepage_promotion", "Homepage promotion")], max_length=32)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateTimeField(default=timezone.now)),
                ("end_date", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="promoted_listings", to="suppliers.supplier")),
            ],
            options={"ordering": ["-start_date"]},
        ),
        migrations.CreateModel(
            name="StickerPricing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sticker_type", models.CharField(choices=[("supplier", "Supplier sticker"), ("custom", "Custom branding")], max_length=20)),
                ("price_per_bottle", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8)),
                ("minimum_price_per_bottle", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8)),
                ("maximum_price_per_bottle", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8)),
                ("pricing_mode", models.CharField(choices=[("free", "Free"), ("fixed", "Fixed"), ("range", "Range")], default="fixed", max_length=20)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["sticker_type", "-created_at"]},
        ),
        migrations.CreateModel(
            name="SupplierSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("plan_type", models.CharField(choices=[("free", "Free"), ("pro", "Pro"), ("enterprise", "Enterprise")], default="free", max_length=20)),
                ("price_per_month", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("start_date", models.DateTimeField(default=timezone.now)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscriptions", to="suppliers.supplier")),
            ],
            options={"ordering": ["-start_date"]},
        ),
        migrations.CreateModel(
            name="RevenueTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("revenue_type", models.CharField(choices=[("commission", "Commission"), ("sticker_fee", "Sticker fee"), ("subscription", "Subscription"), ("promoted_listing", "Promoted listing"), ("delivery_margin", "Delivery margin")], max_length=32)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="revenue_transactions", to="orders.order")),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="revenue_transactions", to="suppliers.supplier")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="promotedlisting",
            index=models.Index(fields=["supplier", "active"], name="promoted_supplier_active_idx"),
        ),
        migrations.AddIndex(
            model_name="promotedlisting",
            index=models.Index(fields=["promotion_type"], name="promoted_listing_type_idx"),
        ),
        migrations.AddIndex(
            model_name="revenuetransaction",
            index=models.Index(fields=["created_at"], name="revenue_txn_created_idx"),
        ),
        migrations.AddIndex(
            model_name="revenuetransaction",
            index=models.Index(fields=["supplier", "created_at"], name="rev_txn_supplier_created_idx"),
        ),
        migrations.AddIndex(
            model_name="revenuetransaction",
            index=models.Index(fields=["revenue_type", "created_at"], name="revenue_txn_type_created_idx"),
        ),
        migrations.AddIndex(
            model_name="stickerpricing",
            index=models.Index(fields=["sticker_type", "active"], name="sticker_type_active_idx"),
        ),
        migrations.AddIndex(
            model_name="suppliersubscription",
            index=models.Index(fields=["supplier", "active"], name="supplier_sub_active_idx"),
        ),
        migrations.AddIndex(
            model_name="suppliersubscription",
            index=models.Index(fields=["plan_type"], name="supplier_subscription_plan_idx"),
        ),
        migrations.AddConstraint(
            model_name="commissionconfig",
            constraint=models.CheckConstraint(condition=models.Q(("commission_percentage__gte", 0), ("commission_percentage__lte", 100)), name="revenue_commission_between_0_and_100"),
        ),
        migrations.AddConstraint(
            model_name="commissionconfig",
            constraint=models.CheckConstraint(condition=models.Q(("delivery_margin_percentage__gte", 0), ("delivery_margin_percentage__lte", 100)), name="revenue_delivery_margin_between_0_and_100"),
        ),
        migrations.AddConstraint(
            model_name="commissionconfig",
            constraint=models.UniqueConstraint(condition=models.Q(("active", True)), fields=("active",), name="revenue_single_active_commission_config"),
        ),
        migrations.AddConstraint(
            model_name="promotedlisting",
            constraint=models.CheckConstraint(condition=models.Q(("amount__gte", 0)), name="promoted_listing_amount_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="revenuetransaction",
            constraint=models.CheckConstraint(condition=models.Q(("amount__gte", 0)), name="revenue_txn_amount_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="revenuetransaction",
            constraint=models.UniqueConstraint(condition=models.Q(("order__isnull", False)), fields=("order", "revenue_type"), name="revenue_single_order_type_transaction"),
        ),
        migrations.AddConstraint(
            model_name="stickerpricing",
            constraint=models.CheckConstraint(condition=models.Q(("price_per_bottle__gte", 0)), name="sticker_price_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="stickerpricing",
            constraint=models.CheckConstraint(condition=models.Q(("minimum_price_per_bottle__gte", 0)), name="sticker_min_price_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="stickerpricing",
            constraint=models.CheckConstraint(condition=models.Q(("maximum_price_per_bottle__gte", 0)), name="sticker_max_price_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="stickerpricing",
            constraint=models.CheckConstraint(condition=models.Q(("maximum_price_per_bottle__gte", models.F("minimum_price_per_bottle"))), name="sticker_max_gte_min"),
        ),
        migrations.AddConstraint(
            model_name="stickerpricing",
            constraint=models.UniqueConstraint(condition=models.Q(("active", True)), fields=("sticker_type", "active"), name="sticker_single_active_type_pricing"),
        ),
        migrations.AddConstraint(
            model_name="suppliersubscription",
            constraint=models.CheckConstraint(condition=models.Q(("price_per_month__gte", 0)), name="subscription_price_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="suppliersubscription",
            constraint=models.UniqueConstraint(condition=models.Q(("active", True)), fields=("supplier", "active"), name="supplier_single_active_subscription"),
        ),
        migrations.RunPython(seed_default_revenue_config, migrations.RunPython.noop),
    ]
