# Generated by Codex on 2026-05-26

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations


def money(value):
    return (value or Decimal("0.00")).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


def backfill_order_revenue(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    OrderItem = apps.get_model("orders", "OrderItem")
    RevenueTransaction = apps.get_model("revenue", "RevenueTransaction")

    for order in Order.objects.all().iterator():
        bottle_cost = Decimal("0.00")
        customization_cost = Decimal("0.00")

        for item in OrderItem.objects.filter(order=order).select_related("product"):
            unit_price = item.unit_price_snapshot or item.product.price_per_unit
            sticker_fee = Decimal("4.00") if item.sticker_type == "custom" else Decimal("0.00")
            item.sticker_fee_snapshot = money(sticker_fee)
            item.customization_total = money(sticker_fee * item.quantity)
            item.line_total = money((unit_price * item.quantity) + item.customization_total)
            item.save(update_fields=["sticker_fee_snapshot", "customization_total", "line_total"])
            bottle_cost += money(unit_price * item.quantity)
            customization_cost += item.customization_total

        delivery_cost = money(order.delivery_cost)
        total = money(bottle_cost + customization_cost + delivery_cost)
        commission_revenue = money(bottle_cost * Decimal("0.12"))
        platform_revenue = money(commission_revenue + customization_cost)
        supplier_payout = money(total - platform_revenue)

        order.subtotal_price = money(bottle_cost)
        order.customization_total = money(customization_cost)
        order.delivery_cost = delivery_cost
        order.commission_percentage_snapshot = Decimal("12.00")
        order.commission_revenue = commission_revenue
        order.delivery_margin_revenue = Decimal("0.00")
        order.platform_revenue = platform_revenue
        order.supplier_payout = supplier_payout
        order.total_price = total
        order.save(
            update_fields=[
                "subtotal_price",
                "customization_total",
                "delivery_cost",
                "commission_percentage_snapshot",
                "commission_revenue",
                "delivery_margin_revenue",
                "platform_revenue",
                "supplier_payout",
                "total_price",
            ]
        )

        if order.payment_status != "captured" or not order.assigned_supplier_id:
            continue

        transaction_payloads = [
            ("commission", commission_revenue, "Marketplace commission"),
            ("sticker_fee", customization_cost, "Custom branding fee"),
        ]
        for revenue_type, amount, description in transaction_payloads:
            if amount <= Decimal("0.00"):
                continue
            RevenueTransaction.objects.update_or_create(
                order=order,
                revenue_type=revenue_type,
                defaults={
                    "supplier_id": order.assigned_supplier_id,
                    "amount": money(amount),
                    "currency": order.currency,
                    "description": description,
                    "metadata": {
                        "order_total": str(order.total_price),
                        "supplier_payout": str(order.supplier_payout),
                    },
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("revenue", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(backfill_order_revenue, migrations.RunPython.noop),
    ]
